### ISSUE TITLE
Error opening bounding box dialog

### ISSUE THREAD

**Issue by alonyan** [PreibischLab/multiview-reconstruction#24]
Hi all,
I'm experiencing a weird error: When I try to interactively define a bounding box, the dialog window doesn't open and I get the error below. This has worked with no issue 2-3 days ago. I've even downloaded a fresh ImageJ and got the same issue, so I don't think it's something I broke.

Any clues for what might be going on?

Thanks,
Alon

```
Exception in thread "Thread-7" java.lang.NoClassDefFoundError: org/scijava/listeners/ListenableVar
	at bdv.tools.boundingbox.TransformedBoxOverlay.<init>(TransformedBoxOverlay.java:110)
	at bdv.tools.boundingbox.BoundingBoxDialog.<init>(BoundingBoxDialog.java:144)
	at bdv.tools.boundingbox.BoundingBoxDialog.<init>(BoundingBoxDialog.java:99)
	at spim.process.fusion.boundingbox.BigDataViewerBoundingBox$1.<init>(BigDataViewerBoundingBox.java:150)
	at spim.process.fusion.boundingbox.BigDataViewerBoundingBox.queryParameters(BigDataViewerBoundingBox.java:149)
	at spim.fiji.plugin.Define_Bounding_Box.defineBoundingBox(Define_Bounding_Box.java:136)
	at spim.fiji.plugin.Define_Bounding_Box.defineBoundingBox(Define_Bounding_Box.java:82)
	at spim.fiji.spimdata.explorer.popup.BoundingBoxPopup$MyActionListener$1.run(BoundingBoxPopup.java:79)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.scijava.listeners.ListenableVar
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

```

**Comment by hoerldavid** [comment]
Hi @alonyan ,

This is due to an update in BigDataViewer (it came up a second time, see https://github.com/PreibischLab/BigStitcher/issues/53 for details). I notified @tpietzsch, he'll have it fixed in no time (thx :) ).

Best,
David

**Comment by hoerldavid** [comment]
... and the fix is here already. Just update your Fiji and the error should be gone!
**Thanks @tpietzsch for fixing this upstream issue so quickly!!**

Best,
David
