### ISSUE TITLE
ClassCastException in deconvolution step

### ISSUE THREAD

**Issue by hajaalin** [PreibischLab/multiview-reconstruction#3]
We tested the multiview reconstruction plugin with your example dataset (Drosophila, 7 angles). We used CUDA with DLLs built according to your instructions. In the deconvolution step we got this error:
```
...
[924, 1060, 934] -> [1435, 1571, 1445], dimensions (512, 512, 512)
[1396, 1060, 934] -> [1907, 1571, 1445], dimensions (512, 512, 512)

Exception in thread "Thread-165" java.lang.ClassCastException: net.preibisch.mvrecon.process.deconvolution.iteration.sequential.ComputeBlockSeqThreadCUDAFactory cannot be cast to net.preibisch.mvrecon.process.deconvolution.iteration.sequential.ComputeBlockSeqThreadCPUFactory
        at net.preibisch.mvrecon.fiji.plugin.Image_Deconvolution.deconvolve(Image_Deconvolution.java:227)
        at net.preibisch.mvrecon.fiji.plugin.Image_Deconvolution.deconvolve(Image_Deconvolution.java:86)
        at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.DeconvolutionPopup$MyActionListener$1.run(DeconvolutionPopup.java:82)
        at java.lang.Thread.run(Thread.java:745)

```
Thanks,
Harri

**Comment by StephanPreibisch** [comment]
Hi, should be fixed with commit https://github.com/PreibischLab/multiview-reconstruction/commit/5261b906058769b3007fbd9601e878c4bcc57ce3

Making a new Fiji release now ...
