### ISSUE TITLE
Issue with Pairwise shit calculation in latest versions

### ISSUE THREAD

**Issue by lguerard** [PreibischLab/multiview-reconstruction#40]
Hi all,

In the latest version of MVR, calculating the pairwise shift always give this error : 

```log
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.preibisch.mvrecon.process.downsampling.DownsampleTools.openAndDownsample(Lmpicbg/spim/data/generic/sequence/BasicImgLoader;Lmpicbg/spim/data/sequence/ViewId;Lnet/imglib2/realtransform/AffineTransform3D;[JZZ)Lnet/imglib2/RandomAccessibleInterval;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.preibisch.stitcher.algorithm.globalopt.TransformationTools.computePairs(TransformationTools.java:639)
	at net.preibisch.stitcher.plugin.Calculate_Pairwise_Shifts.processPhaseCorrelation(Calculate_Pairwise_Shifts.java:179)
	at net.preibisch.stitcher.plugin.Calculate_Pairwise_Shifts.run(Calculate_Pairwise_Shifts.java:149)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runPlugIn(IJ.java:203)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at ij.IJ.run(IJ.java:319)
	at ij.IJ.run(IJ.java:330)
	at ij.macro.Functions.doRun(Functions.java:703)
	at ij.macro.Functions.doFunction(Functions.java:99)
	at ij.macro.Interpreter.doStatement(Interpreter.java:281)
	at ij.macro.Interpreter.doStatements(Interpreter.java:267)
	at ij.macro.Interpreter.run(Interpreter.java:163)
	at ij.macro.Interpreter.run(Interpreter.java:93)
	at ij.macro.Interpreter.run(Interpreter.java:107)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:162)
	at ij.IJ.runMacro(IJ.java:158)
	at ij.IJ.runMacro(IJ.java:147)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1174)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1170)
	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:1121)
	at net.imagej.legacy.IJ1Helper.runMacro(IJ1Helper.java:1170)
	at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:145)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:164)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoSuchMethodError: net.preibisch.mvrecon.process.downsampling.DownsampleTools.openAndDownsample(Lmpicbg/spim/data/generic/sequence/BasicImgLoader;Lmpicbg/spim/data/sequence/ViewId;Lnet/imglib2/realtransform/AffineTransform3D;[JZZ)Lnet/imglib2/RandomAccessibleInterval;
	at net.preibisch.stitcher.algorithm.GroupedViewAggregator.aggregate(GroupedViewAggregator.java:381)
	at net.preibisch.stitcher.algorithm.globalopt.TransformationTools.computeStitching(TransformationTools.java:271)
	at net.preibisch.stitcher.algorithm.globalopt.TransformationTools$2.call(TransformationTools.java:586)
	at net.preibisch.stitcher.algorithm.globalopt.TransformationTools$2.call(TransformationTools.java:568)
	... 4 more
```

This used to work in older versions as reported on the forum [here](https://forum.image.sc/t/bigstitcher-advanced-grouping-group-time-points-not-working-in-recent-versions/77294).

Any ideas ? 

Thanks for your help !

**Comment by StephanPreibisch** [comment]
Hi, it should be fixed now @lguerard, could you please try after updating Fiji? Thanks so much for reporting!!!

**Comment by lguerard** [comment]
Hi @StephanPreibisch thanks a lot !! I can confirm that it's now working on the latest version ! :)
